export const ORDER_STATES = Object.freeze({
  PENDING: "PENDING",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  PAID: "PAID",
  PREPARING: "PREPARING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
  DISPUTED: "DISPUTED",
});

const LEGACY_ORDER_STATES = {
  pending: ORDER_STATES.PENDING,
  paid: ORDER_STATES.PAID,
  shipped: ORDER_STATES.SHIPPED,
  delivered: ORDER_STATES.DELIVERED,
  review: ORDER_STATES.DELIVERED,
  completed: ORDER_STATES.COMPLETED,
  cancelled: ORDER_STATES.CANCELLED,
  canceled: ORDER_STATES.CANCELLED,
  refunded: ORDER_STATES.REFUNDED,
  failed: ORDER_STATES.CANCELLED,
  disputed: ORDER_STATES.DISPUTED,
};

export function normalizeOrderStatus(status) {
  if (!status) return ORDER_STATES.PENDING;
  const raw = String(status).trim();
  return LEGACY_ORDER_STATES[raw.toLowerCase()] || raw.toUpperCase();
}

export function canTransitionOrder(from, to, actorRole) {
  const current = normalizeOrderStatus(from);
  const next = normalizeOrderStatus(to);
  const allowed = {
    [ORDER_STATES.PENDING]: [ORDER_STATES.PAYMENT_PROCESSING, ORDER_STATES.CANCELLED],
    [ORDER_STATES.PAYMENT_PROCESSING]: [ORDER_STATES.PAID, ORDER_STATES.CANCELLED],
    [ORDER_STATES.PAID]: [ORDER_STATES.PREPARING, ORDER_STATES.SHIPPED, ORDER_STATES.CANCELLED, ORDER_STATES.REFUNDED, ORDER_STATES.DISPUTED],
    [ORDER_STATES.PREPARING]: [ORDER_STATES.SHIPPED, ORDER_STATES.CANCELLED, ORDER_STATES.DISPUTED],
    [ORDER_STATES.SHIPPED]: [ORDER_STATES.DELIVERED, ORDER_STATES.COMPLETED, ORDER_STATES.DISPUTED],
    [ORDER_STATES.DELIVERED]: [ORDER_STATES.COMPLETED, ORDER_STATES.DISPUTED],
    [ORDER_STATES.DISPUTED]: [ORDER_STATES.REFUNDED, ORDER_STATES.COMPLETED, ORDER_STATES.CANCELLED],
  };

  if (actorRole === "buyer" && next === ORDER_STATES.SHIPPED) return false;
  if (actorRole === "seller" && [ORDER_STATES.DELIVERED, ORDER_STATES.COMPLETED].includes(next)) return false;
  return allowed[current]?.includes(next) || false;
}
